version: "3.7"

services: 
    client:
        container_name: nomfilx_client
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            ["3000:3000"]
        environment: 
            - NODE_ENV=development
        stdin_open: true
        tty: true
    server:
        container_name: nofilx_server
        build:
            context: ./server
            dockerfile: Dockerfile
        ports: 
            ["5000:5000"]